// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proj1.Data;

#nullable disable

namespace proj1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proj1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Economy"
                        });
                });

            modelBuilder.Entity("proj1.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Technology is booming.",
                            ImageUrl = "https://placehold.co/600x400",
                            IsPublished = true,
                            PublishDate = new DateTime(2025, 11, 23, 19, 30, 47, 83, DateTimeKind.Local).AddTicks(9776),
                            Title = "Tech Boom"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "Team A won.",
                            ImageUrl = "https://placehold.co/600x400",
                            IsPublished = true,
                            PublishDate = new DateTime(2025, 11, 23, 19, 30, 47, 83, DateTimeKind.Local).AddTicks(9778),
                            Title = "Sports Update"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "Economy is growing.",
                            ImageUrl = "https://placehold.co/600x400",
                            IsPublished = false,
                            PublishDate = new DateTime(2025, 11, 23, 19, 30, 47, 83, DateTimeKind.Local).AddTicks(9780),
                            Title = "Economy Growth"
                        });
                });

            modelBuilder.Entity("proj1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 23, 19, 30, 47, 83, DateTimeKind.Local).AddTicks(9491),
                            Email = "admin@newsportal.com",
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 23, 19, 30, 47, 83, DateTimeKind.Local).AddTicks(9493),
                            Email = "user@newsportal.com",
                            PasswordHash = "user123",
                            Role = "User",
                            Username = "standard_user"
                        });
                });

            modelBuilder.Entity("proj1.Models.News", b =>
                {
                    b.HasOne("proj1.Models.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("proj1.Models.Category", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
